version: '3.7'
services:
  angular:
    build:
      context: ..
      dockerfile: docker/angular/Dockerfile
      target: dev
    user: node
    env_file:
      - '.env'
    ports:
      - '${NODEJS_CONTAINER_SERVE_PORT}:4200'
      - '${NODEJS_CONTAINER_TEST_PORT}:9876'
    tty: true
    volumes:
      - '..:/usr/src:cached'
